// AUTO-GENERATED by scripts/generate-apercu-font.mjs — do not edit by hand.
// No Apercu font files found in src/fonts/apercu/ (see README.md there).
// next/font/local is intentionally NOT called here — it would fail the
// build if pointed at a missing file. Typography falls back to Tahoma via
// the CSS stack in src/app/globals.css.
export const apercuVariable = "";
export const apercuClassName = "";
